# 服务接口配置
server:
  port: 8101
  servlet:
    context-path: /
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        domain: 122.51.41.152
spring:
  application:
    name: binapi-backend
  # MySQL 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.41.152:3306/binapi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: binapi_root
    password: 6YLzYAjdiafdNr3Y
  # Redis 配置
  data:
    redis:
      host: 122.51.41.152
      port: 6379
      database: 0
      timeout: 5000
      password: 123456
# swagger 接口配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bin.binapibackend.controller
# knife4j增强配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
  setting:
    language: zh_cn
# dubbo配置
dubbo:
  application:
    qosPort: 4444
    name: dubbo-provider
    logger: slf4j
  protocol:
    name: dubbo
    port: -1
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    address: nacos://122.51.41.152:8848?username=nacos&password=nacos
    id: nacos-registry

# 跨域配置
cors:
  allowed-origins: "http://localhost:8000,http://122.51.41.152"